spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
server:
    address: 127.0.0.1
    port: 8081
payment:
    age: 28
    notify-url: http://localhost:8080/hello1




---
spring:
  profiles: test
server:
  address: 127.0.0.1
  port: 8082
---
spring:
  profiles: product
server:
  port: 80
  address: 127.0.0.1